version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    working_dir: /api-gateway
    command: >
      sh -c "sleep 15 && npm run start:prod"
    environment:
      - TZ=UTC
      - PORT=4000
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://root:12345@rabbitmq:5672/
      - JWT_SECRET=PzP0uYbDzdydnKytSqaVrtedHStetdpZ4k84wNCi8igBD9nYGiU7653euf0j
      - JWT_ACCESS_TOKEN_EXPIRE_IN=15m
      - JWT_REFRESH_TOKEN_EXPIRE_IN=15d
    ports:
      - 4000:4000
    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq

  profile-service:
    build:
      context: ./profile-service
      dockerfile: Dockerfile
    container_name: profile-service
    working_dir: /profile-service
    command: >
      sh -c "sleep 15 && npx prisma db push && npm run start:prod"
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:12345@mysql:3306/profile-service
      - RABBITMQ_URL=amqp://root:12345@rabbitmq:5672/
    networks:
      - mysql-net
      - rabbitmq-net
    depends_on:
      - mysql
      - rabbitmq

  session-service:
    build:
      context: ./session-service
      dockerfile: Dockerfile
    container_name: session-service
    working_dir: /session-service
    command: >
      sh -c "sleep 15 && npx prisma db push && npm run start:prod"
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:12345@mysql:3306/session-service
      - RABBITMQ_URL=amqp://root:12345@rabbitmq:5672/
    networks:
      - mysql-net
      - rabbitmq-net
    depends_on:
      - mysql
      - rabbitmq

  shortener-service:
    build:
      context: ./shortener-service
      dockerfile: Dockerfile
    container_name: shortener-service
    working_dir: /shortener-service
    command: >
      sh -c "sleep 15 && npx prisma db push && npm run start:prod"
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:12345@mysql:3306/shortener-service
      - RABBITMQ_URL=amqp://root:12345@rabbitmq:5672/
    networks:
      - rabbitmq-net
      - mysql-net
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    expose:
      - 3306:3306
    networks:
      - mysql-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    restart: unless-stopped
    expose:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    name: shortener_rabbitmq-net
    driver: bridge
  mysql-net:
    name: shortener_mysql-net
    driver: bridge
