
services:
  shortener_service:
    depends_on:
      - db
    build:
      context: ./shortener-service
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - db_net 
  redirector_service:
    depends_on:
      - db
    build:
      context: ./redirector-service
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - db_net
  db:
    image: scylladb/scylla
    container_name: scylladb
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
      - ./shortener-service/internal/infrastructure/scylladb/init.cql:/init.cql
    networks:
      - db_net
  click-house:
    image: clickhouse/clickhouse-server
    container_name: click-house
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 18123:8123
      - 19000:9000
    environment:
      - CLICKHOUSE_PASSWORD=1234567
    volumes:
      - click-house_data:/var/lib/clickhouse/
    networks:
      - db_net
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"  
      - "29093:29093"
    environment:
      CLUSTER_ID: Mf2Ue57NzU6EX9zZJvD2Mw==
      KAFKA_NODE_ID: 1
      KAFKA_KRAFT_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_KRAFT_MODE: "true"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_net
    command:
      - sh
      - -c
      - |
        echo "Starting Kafka in KRaft mode..."
        /etc/confluent/docker/run
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIGURATION_ENABLED: "true"
    networks:
      - kafka_net

volumes:
  scylla_data:
  click-house_data:

networks:
  db_net:
  kafka_net: